# @format

version: "3.7"

services:
    # Database service
    db:
        image: ${AWS_ECR_URI}/ignite-db:latest
        build: ./postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: ${ADMIN_PASSWORD}
            POSTGRES_USER: ${ADMIN_USER}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - db-data:/var/lib/postgresql/data
        networks:
            - ignite-net
        restart: on-failure

    pgadmin:
        image: dpage/pgadmin4:5.1
        build: ./pg_admin
        environment:
            PGADMIN_DEFAULT_EMAIL: postgres@ignite.app
            PGADMIN_DEFAULT_PASSWORD: postgres
        ports:
            - "5050:80"
        networks:
            - ignite-net

    # Keycloak service for authentication
    auth:
        build: ./keycloak
        ports:
            - "8080:8080"
        networks:
            - ignite-net
        command: ["start-dev"]
        environment:
            KEYCLOAK_ADMIN: ${ADMIN_USER}
            KEYCLOAK_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
        depends_on:
            - db
        restart: always

    # Mail service
    mail:
        image: mailhog/mailhog:v1.0.1
        build: ./mailhog
        ports:
            - "8025:8025"
        restart: always

    # Client service
    client:
        build: ./Client
        ports:
            - "3000:3000"
        volumes:
            - ./Client:/app
        restart: on-failure

    # Server service
    server:
        build: ./Server
        depends_on:
            - db
        ports:
            - "8000:8000"
        volumes:
            - ./server:/app
        restart: on-failure
        networks:
            - ignite-net

    # Workflows service
    # workflows:
    #     image: prefect/prefect:0.15.7
    #     ports:
    #         - "8081:8081"
    #     restart: on-failure

networks:
    ignite-net:

volumes:
    db-data:
        driver: local
