# @format

name: CI-dev-pipeline
on:
    # Triggers the workflow on push or pull request events but only for the develop branch
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    build:
        # The type of runner that the job will run on
        name: Build and Push to ECR
        runs-on: ubuntu-latest
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - name: Checkout
              uses: actions/checkout@v2

            - name: "Create env file"
              run: |
                  echo "${{ secrets.ENV_FILE }}" > .env

            - name: Test File sys
              run: |
                  echo ---File System---
                  ls -a

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
                  aws-region: us-east-2

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1

            - name: Build, Tag, Push Docker Images
              id: build-images
              env:
                  ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry}}
                  ECR_REPOSITORY: ignitehub-registry
                  IMAGE_TAG: latest
              run: |
                  echo --Building containers--
                  docker-compose -f docker-compose.yaml up -d --build
                  docker-compose push
                  docker push $ECR_REGISTRY/ignite-client:latest
                  docker push $ECR_REGISTRY/ignite-auth:latest
                  docker push $ECR_REGISTRY/ignite-mail:latest
                  docker push $ECR_REGISTRY/ignite-db-admin:latest
                  docker push $ECR_REGISTRY/ignite-db:latest
                  docker push $ECR_REGISTRY/ignite-api:latest
